/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.0.0
 *
 * Project: 'FreeRTOS_FatFs_LVGL__AT_START_F403A' 
 * Target:  'AT32F403A_Debug' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* LVGL::LVGL&LVGL9:Essential@9.4.0 */
/*! \brief use lv_config_cmsis.h which will be pre-included */
#define LV_CONF_SKIP
#define LV_LVGL_H_INCLUDE_SIMPLE    1


#endif /* PRE_INCLUDE_GLOBAL_H */
