/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.0.0
 *
 * Project: 'FreeRTOS_FatFs_LVGL__AT_START_F403A' 
 * Target:  'AT32F403A_Debug' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "at32f403a_407.h"

/* ARM::CMSIS-Compiler:OS Interface:CMSIS-RTOS2@2.1.0 */
#define RTE_CMSIS_Compiler_OS_Interface       /* Compiler OS Interface */
#define RTE_CMSIS_Compiler_OS_Interface_RTOS2 /* Compiler OS Interface: CMSIS-RTOS2 */
/* Features */
#define RTE_CMSIS_Compiler_OS_Interface_RTOS2_LOCKS     /* Implements _mutex functions */
#define RTE_CMSIS_Compiler_OS_Interface_RTOS2_LIBSPACE  /* Implements per-thread static data management */
/* ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* ARM::CMSIS:RTOS2:FreeRTOS&Cortex-M@11.2.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_FreeRTOS        /* CMSIS-RTOS2 FreeRTOS */
/* ARM::RTOS&FreeRTOS:Config&CMSIS RTOS2@11.2.0 */
#define RTE_RTOS_FreeRTOS_CONFIG_RTOS2  /* RTOS FreeRTOS Config for CMSIS RTOS2 API */
/* ARM::RTOS&FreeRTOS:Core&Cortex-M@11.2.0 */
#define RTE_RTOS_FreeRTOS_CORE          /* RTOS FreeRTOS Core */
/* ARM::RTOS&FreeRTOS:Event Groups@11.2.0 */
#define RTE_RTOS_FreeRTOS_EVENTGROUPS   /* RTOS FreeRTOS Event Groups */
/* ARM::RTOS&FreeRTOS:Heap&Heap_4@11.2.0 */
#define RTE_RTOS_FreeRTOS_HEAP_4        /* RTOS FreeRTOS Heap 4 */
/* ARM::RTOS&FreeRTOS:Timers@11.2.0 */
#define RTE_RTOS_FreeRTOS_TIMERS        /* RTOS FreeRTOS Timers */
/* ArteryTek::Device:at32f403a_407_firmware_library:acc@2.0.0 */
#define RTE_DEVICE_STDPERIPHERALS_ACC
/* ArteryTek::Device:at32f403a_407_firmware_library:adc@2.0.0 */
#define RTE_DEVICE_STDPERIPHERALS_ADC
/* ArteryTek::Device:at32f403a_407_firmware_library:bpr@2.0.0 */
#define RTE_DEVICE_STDPERIPHERALS_BPR
/* ArteryTek::Device:at32f403a_407_firmware_library:crm@2.0.0 */
#define RTE_DEVICE_STDPERIPHERALS_CRM
/* ArteryTek::Device:at32f403a_407_firmware_library:debug@2.0.0 */
#define RTE_DEVICE_STDPERIPHERALS_DEBUG
/* ArteryTek::Device:at32f403a_407_firmware_library:dma@2.0.0 */
#define RTE_DEVICE_STDPERIPHERALS_DMA
/* ArteryTek::Device:at32f403a_407_firmware_library:exint@2.0.0 */
#define RTE_DEVICE_STDPERIPHERALS_EXINT
/* ArteryTek::Device:at32f403a_407_firmware_library:flash@2.0.0 */
#define RTE_DEVICE_STDPERIPHERALS_FLASH
/* ArteryTek::Device:at32f403a_407_firmware_library:gpio@2.0.0 */
#define RTE_DEVICE_STDPERIPHERALS_GPIO
/* ArteryTek::Device:at32f403a_407_firmware_library:i2c@2.0.0 */
#define RTE_DEVICE_STDPERIPHERALS_I2C
/* ArteryTek::Device:at32f403a_407_firmware_library:misc@2.0.0 */
#define RTE_DEVICE_STDPERIPHERALS_MISC
/* ArteryTek::Device:at32f403a_407_firmware_library:pwc@2.0.0 */
#define RTE_DEVICE_STDPERIPHERALS_PWC
/* ArteryTek::Device:at32f403a_407_firmware_library:rtc@2.0.0 */
#define RTE_DEVICE_STDPERIPHERALS_RTC
/* ArteryTek::Device:at32f403a_407_firmware_library:spi@2.0.0 */
#define RTE_DEVICE_STDPERIPHERALS_SPI
/* ArteryTek::Device:at32f403a_407_firmware_library:tmr@2.0.0 */
#define RTE_DEVICE_STDPERIPHERALS_TMR
/* ArteryTek::Device:at32f403a_407_firmware_library:usart@2.0.0 */
#define RTE_DEVICE_STDPERIPHERALS_USART
/* ArteryTek::Device:at32f403a_407_firmware_library:usb@2.0.0 */
#define RTE_DEVICE_STDPERIPHERALS_USB
/* LVGL::LVGL&LVGL9:Essential@9.4.0 */
/*! \brief Enable LVGL */
#define RTE_GRAPHICS_LVGL
/* LVGL::LVGL&LVGL9:Libraries and Others:File Explorer@9.4.0 */
/*! \brief enable file explorer support */
#define LV_USE_FILE_EXPLORER         1
/* LVGL::LVGL&LVGL9:Libraries and Others:Lib Filesystem&FATFS@9.4.0 */
/*! \brief enable FATFS support */
#define LV_USE_FS_FATFS         1
/* LVGL::LVGL&LVGL9:OS Abstraction Layer&FreeRTOS@9.4.0 */
#define LV_USE_OS   LV_OS_FREERTOS


#endif /* RTE_COMPONENTS_H */
